name: API Integration Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: "${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}"
          restore-keys: "${{ runner.os }}-m2"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install httpyac
        run: npm install -g httpyac

      - name: Build Spring Boot Application
        run: ./mvnw clean compile

      - name: Start Spring Boot Application
        run: |
          ./mvnw spring-boot:run &
          echo $! > app.pid
        env:
          SPRING_PROFILES_ACTIVE: test

      - name: Wait for application to start
        run: |
          echo "Waiting for application to start..."
          for i in {1..30}; do
            if curl -f http://localhost:8080/actuator/health 2>/dev/null || curl -f http://localhost:8080/users 2>/dev/null; then
              echo "Application is ready!"
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done
          
          # Final check
          if ! curl -f http://localhost:8080/users 2>/dev/null; then
            echo "Application failed to start properly"
            exit 1
          fi

      - name: Run HTTP Client Tests
        run: |
          echo "Running HTTP tests with httpyac..."
          httpyac rest-api.http --all

      - name: Stop Spring Boot Application
        if: always()
        run: |
          if [ -f app.pid ]; then
            PID=$(cat app.pid)
            kill $PID || true
            rm app.pid
          fi
          # Also kill any java processes that might be running
          pkill -f "spring-boot:run" || true